/*
    Chương trình minh họa exception trong java
    + Khai báo một mảng a có 5 phần tử
    + Vòng lặp duyệt từ a[0] đến a[9] và in ra giá trị của a[i] => Xuất hiện ngoại lệ do vượt quá chỉ số mảng
    => thông báo lỗi: Index 5 out of bounds for length 5
    + Sử dụng khối try ... catch để xử lý các ngoại lệ

    Có hai loại ngoại lệ trong java là Checked exception và Runtime Exception
    1. Checked Exception: là ngoại lệ kiểm tra bởi trình biên dịch (compiler). Nếu mã có xảy ra ngoại lệ thì phải xử lý qua cơ chế try..catch (ví dụ: IOException)
    + Các ngoại lệ này thường dự đoán trước và có liên quan đến các tính huống như nhập/xuất, truy xuất CSDL, tệp tin,...
    2. Runtime exception: Đây là ngoại lệ chỉ xảy ra khi chương trình đang chạy. Trình biên dịch không bắt buộc phải xử lý hoặc khai báo chúng
    ví dụ: NullPointerException, ArrayIndexOutOfBoundsException,....
    + Thường do lỗi logic của lập trình viên, ví dụ như truy cập phần tử không tồn tại trong mảng.
    

*/


public class Main{
	public static void main(String[] args){	
        int[] a ={1,2,3,4,5};
        int n=10;
        try{
            for(int i=0; i<n; i++)
                System.out.println("a[" + i + "]=" + a[i]);
        } catch(Exception e){
            System.out.println(e);
        }
        
    }
}   
------------------------------
Vi du: Checked Exception
/*
    Chương trình minh họa exception trong java
    + Khai báo một mảng a có 5 phần tử
    + Vòng lặp duyệt từ a[0] đến a[9] và in ra giá trị của a[i] => Xuất hiện ngoại lệ do vượt quá chỉ số mảng
    => thông báo lỗi: Index 5 out of bounds for length 5
    + Sử dụng khối try ... catch để xử lý các ngoại lệ

    Có hai loại ngoại lệ trong java là Checked exception và Runtime Exception
    1. Checked Exception: là ngoại lệ kiểm tra bởi trình biên dịch (compiler). Nếu mã có xảy ra ngoại lệ thì phải xử lý qua cơ chế try..catch (ví dụ: IOException)
    + Các ngoại lệ này thường dự đoán trước và có liên quan đến các tính huống như nhập/xuất, truy xuất CSDL, tệp tin,...
    2. Runtime exception: Đây là ngoại lệ chỉ xảy ra khi chương trình đang chạy. Trình biên dịch không bắt buộc phải xử lý hoặc khai báo chúng
    ví dụ: NullPointerException, ArrayIndexOutOfBoundsException,....
    + Thường do lỗi logic của lập trình viên, ví dụ như truy cập phần tử không tồn tại trong mảng.


*/

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
public class Main{
	public static void main(String[] args){	
         try{
             BufferedReader reader = new BufferedReader(new FileReader("example.txt"));
             String line = reader.readLine();
             System.out.println(line);
             reader.close();
         }
         catch(IOException e){
             System.out.println("Da xay ra loi khi doc file, " + e.getMessage());
         }
        
    }
}   
----------------------------------------------
Vi du: Runtime Exception
/*
    Chương trình minh họa exception trong java
    + Khai báo một mảng a có 5 phần tử
    + Vòng lặp duyệt từ a[0] đến a[9] và in ra giá trị của a[i] => Xuất hiện ngoại lệ do vượt quá chỉ số mảng
    => thông báo lỗi: Index 5 out of bounds for length 5
    + Sử dụng khối try ... catch để xử lý các ngoại lệ

    Có hai loại ngoại lệ trong java là Checked exception và Runtime Exception
    1. Checked Exception: là ngoại lệ kiểm tra bởi trình biên dịch (compiler). Nếu mã có xảy ra ngoại lệ thì phải xử lý qua cơ chế try..catch (ví dụ: IOException)
    + Các ngoại lệ này thường dự đoán trước và có liên quan đến các tính huống như nhập/xuất, truy xuất CSDL, tệp tin,...
    2. Runtime exception: Đây là ngoại lệ chỉ xảy ra khi chương trình đang chạy. Trình biên dịch không bắt buộc phải xử lý hoặc khai báo chúng
    ví dụ: NullPointerException, ArrayIndexOutOfBoundsException,....
    + Thường do lỗi logic của lập trình viên, ví dụ như truy cập phần tử không tồn tại trong mảng.


*/

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
public class Main{
	public static void main(String[] args){	
         int a = 10;
         int b=0;
         try{
             int c = a/b;
             System.out.println("Ket qua la: " + c);
         }catch(ArithmeticException e)
         {
             System.out.println("Da xay ra loi: " + e.getMessage());
         }
        
    }
}   
===============================================
Vi du ve throw exception
/*
   throw exception là một có chế xử lý ngoại lệ trong java, khi lập trình nếu cần xử lý một tình huống đặc biệt nào đó, chúng ta sẽ sử dụng từ khóa throw để "ném" ra một ngoại lệ

*/

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
public class Main{
	
    public static void checkAge(int age){
        if(age < 18){
            throw new IllegalArgumentException("Ban chua du tuoi de su dung dich vu nay.");
        }
        System.out.println("OK, xin moi ban trai nghiem dich vu.");
    }

    public static void main(String[] args){	
         int age;
         Scanner sc = new Scanner(System.in);
         System.out.print("Nhap tuoi: ");
         age = Integer.parseInt(sc.nextLine());
         try{
             checkAge(age);
         }catch(IllegalArgumentException e){
             System.out.println("Da xay ra loi: " + e.getMessage());
         }

        
    }
} 
==============================================
Vi du ve: Excaption Propagation trong java
/*
   Exception Propagation là quá trình lan truyền ngoại lệ trong java, khi một phương thức A gọi một phương thức B, nếu phương thức B không xử lý ngoại lệ,
   không dùng try...catch, thì ngoại lệ đó sẽ được chuyển lên phương thức gọi nó (phương thức A) và quá trình lan truyền sẽ tiếp tục như vậy cho đến khi ngoại lệ được xử lý
   hoặc đến hàm main()

*/

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
public class Main{
	
    public static void A(){
        throw new ArithmeticException("Loi chia cho khong");
    }
    public static void B(){
        A();
    }
    public static void C(){
        try{
            B();
        }catch(ArithmeticException e)
        {
            System.out.println("Ngoai le da duoc xu ly trong phuong thuc C, " + e.getMessage());
        }
    }
    public static void main(String[] args){	
         C();

        
    }
}   



